import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# TODO: this version is generated by biomni and biologically is correct
"""
example response: 
{'drug': 'fluorouracil', 'chembl_id': 'CHEMBL185', 
'smiles': 'O=c1[nH]cc(F)c(=O)[nH]1', 'atc_codes': 
['L01BC02', 'L01BC52'], 'curated_targets': [{'gene_symbol':
'TYMS', 'name': 'thymidylate synthetase', 'ensembl_id': 'ENSG00000176890',
'action_type': 'INHIBITOR', 'mechanism': 'Thymidylate synthase inhibitor',
'source': 'OpenTargets'}]}


{'drug': 'aspirin', 'chembl_id': 'CHEMBL25', 'smiles': 
'CC(=O)Oc1ccccc1C(=O)O', 'atc_codes': ['B01AC06', 'N02BA01', 
'N02BA51', 'A01AD05', 'N02BA71'], 
'curated_targets': [{'gene_symbol': 'PTGS2', 'name': 
'prostaglandin-endoperoxide synthase 2', 'ensembl_id': 
'ENSG00000073756', 'action_type': 'INHIBITOR', 'mechanism': 
'Cyclooxygenase inhibitor', 'source': 'OpenTargets'}, {'gene_symbol': 
'PTGS1', 'name': 'prostaglandin-endoperoxide synthase 1', 'ensembl_id':
'ENSG00000095303', 'action_type': 'INHIBITOR', 'mechanism': 'Cyclooxygenase inhibitor', 
'source': 'OpenTargets'}]}
"""


# ---------------------------
# Resilient session with retries
# ---------------------------
def make_session(retries=3, backoff=1.0, timeout=30):
    session = requests.Session()
    retry = Retry(
        total=retries,
        backoff_factor=backoff,
        status_forcelist=[429, 500, 502, 503, 504],
    )
    adapter = HTTPAdapter(max_retries=retry)
    session.mount("https://", adapter)
    session.mount("http://", adapter)
    session._default_timeout = timeout
    return session


SESSION = make_session()


# ---------------------------
# 1. ChEMBL search
# ---------------------------
def search_chembl(drug_name):
    url = f"https://www.ebi.ac.uk/chembl/api/data/molecule/search?q={drug_name}&format=json"
    r = SESSION.get(url, timeout=SESSION._default_timeout)
    if r.status_code != 200:
        return None
    mols = r.json().get("molecules", [])
    return mols[0] if mols else None


def get_smiles(mol):
    return mol.get("molecule_structures", {}).get("canonical_smiles")


def get_atc(mol):
    return mol.get("atc_classifications", [])


# ---------------------------
# 2. Curated targets — PRIMARY: Open Targets MOA
# ---------------------------
def get_targets_opentargets(chembl_id):
    url = "https://api.platform.opentargets.org/api/v4/graphql"
    query = """
    query DrugMOA($chemblId: String!) {
      drug(chemblId: $chemblId) {
        mechanismsOfAction {
          rows {
            mechanismOfAction
            actionType
            targets {
              id
              approvedSymbol
              approvedName
            }
          }
        }
      }
    }
    """
    try:
        r = SESSION.post(
            url,
            json={"query": query, "variables": {"chemblId": chembl_id}},
            timeout=30,  # increased from 15
        )
        if r.status_code != 200:
            return None
        rows = (
            r.json()
            .get("data", {})
            .get("drug", {})
            .get("mechanismsOfAction", {})
            .get("rows", [])
        )
        targets = []
        for row in rows:
            for t in row.get("targets", []):
                targets.append(
                    {
                        "gene_symbol": t.get("approvedSymbol"),
                        "name": t.get("approvedName"),
                        "ensembl_id": t.get("id"),
                        "action_type": row.get("actionType"),
                        "mechanism": row.get("mechanismOfAction"),
                        "source": "OpenTargets",
                    }
                )
        return targets if targets else None
    except requests.exceptions.Timeout:
        print(
            f"  [!] Open Targets timed out for {chembl_id}, falling back to ChEMBL MOA"
        )
        return None
    except requests.exceptions.RequestException as e:
        print(f"  [!] Open Targets error: {e}, falling back to ChEMBL MOA")
        return None


# ---------------------------
# 3. Curated targets — FALLBACK: ChEMBL mechanism endpoint
# ---------------------------
def get_targets_chembl_moa(chembl_id):
    """
    ChEMBL /mechanism endpoint returns the same curated MOA data
    as DrugBank/Open Targets but served directly from ChEMBL.
    """
    url = f"https://www.ebi.ac.uk/chembl/api/data/mechanism.json?molecule_chembl_id={chembl_id}&limit=100"
    try:
        r = SESSION.get(url, timeout=SESSION._default_timeout)
        if r.status_code != 200:
            return []
        mechanisms = r.json().get("mechanisms", [])
        targets = []
        for m in mechanisms:
            targets.append(
                {
                    "gene_symbol": None,  # not in this endpoint
                    "name": m.get("target_name"),
                    "ensembl_id": None,
                    "action_type": m.get("action_type"),
                    "mechanism": m.get("mechanism_of_action"),
                    "source": "ChEMBL-MOA",
                }
            )
        return targets
    except requests.exceptions.RequestException as e:
        print(f"  [!] ChEMBL MOA fallback also failed: {e}")
        return []


# ---------------------------
# 4. Unified target fetcher
# ---------------------------
def get_curated_targets(chembl_id):
    targets = get_targets_opentargets(chembl_id)
    if targets is None:  # timed out or error
        targets = get_targets_chembl_moa(chembl_id)
    return targets


# ---------------------------
# 5. Main pipeline
# ---------------------------
def get_drug_info(drug_name):
    mol = search_chembl(drug_name)
    if not mol:
        return None
    chembl_id = mol["molecule_chembl_id"]
    return {
        "drug": drug_name,
        "chembl_id": chembl_id,
        "smiles": get_smiles(mol),
        "atc_codes": get_atc(mol),
        "curated_targets": get_curated_targets(chembl_id),
    }


# ---------------------------
# TEST
# ---------------------------
if __name__ == "__main__":
    print(get_drug_info("fluorouracil"))
    print(get_drug_info("aspirin"))
