# generated by copilat

"""
models_higsyn.py

HIGSyn model - Hypergraph-based integration for drug combination synergy prediction.
This is a baseline that uses hypergraph structure to predict drug combination synergy.

The model scores combinations based on the frequency of drugs appearing in known synergistic combinations.
"""

import numpy as np


class HIGSynRunner:
    """
    HIGSyn baseline model using hypergraph information.

    Scores drug combinations based on the degree (frequency of occurrence)
    in the known positive drug combination hypergraph.
    """

    def __init__(self, root, dataset):
        """
        Initialize HIGSynRunner.

        Args:
            root: Root directory containing data files
            dataset: 'breast' or 'lung'
        """
        self.root = root
        self.dataset = dataset
        self.name2degree = {}

    def fit(self, train_items):
        """
        Train by computing degree of each drug in positive combinations.

        Args:
            train_items: List of dicts with keys: drugA, drugB, drugC, label
        """
        drug_degrees = {}

        for item in train_items:
            if int(item.get("label", 0)) == 1:
                for drug_key in ["drugA", "drugB", "drugC"]:
                    drug = str(item.get(drug_key, "")).strip()
                    if drug and drug != ".":
                        drug_degrees[drug] = drug_degrees.get(drug, 0) + 1

        # Normalize degrees
        max_degree = max(drug_degrees.values()) if drug_degrees else 1
        self.name2degree = {
            drug: float(degree) / float(max_degree)
            for drug, degree in drug_degrees.items()
        }

    def score(self, items):
        """
        Score combinations as sum of individual drug degrees.

        Args:
            items: List of dicts with keys: drugA, drugB, drugC

        Returns:
            List of scores (normalized to [0, 1])
        """
        scores = []

        for item in items:
            a = str(item.get("drugA", "")).strip()
            b = str(item.get("drugB", "")).strip()
            c = str(item.get("drugC", "")).strip()

            # Sum of individual drug degrees
            score = (
                self.name2degree.get(a, 0.0)
                + self.name2degree.get(b, 0.0)
                + self.name2degree.get(c, 0.0)
            )
            scores.append(score)

        # Normalize to [0, 1]
        arr = np.array(scores, dtype=float)
        if arr.max() > 0:
            arr = arr / arr.max()

        return arr.tolist()
