# generated by copilat

"""
models_gcn.py

Graph Convolutional Network (GCN) model for drug combination synergy prediction.

GCNs learn representations of nodes (drugs) by aggregating information from their
neighbors in a graph. For drug combinations, we construct a similarity graph where
edges connect drugs with high similarity.
"""

import numpy as np


class GCNRunner:
    """
    GCN baseline model using drug similarity graph.

    This simplified implementation:
    1. Constructs a similarity graph between drugs
    2. Scores combinations based on graph connectivity and degree
    """

    def __init__(self, root, dataset, thresh=0.1):
        """
        Initialize GCNRunner.

        Args:
            root: Root directory containing data files
            dataset: 'breast' or 'lung'
            thresh: Threshold for edge creation in similarity graph (default 0.1)
        """
        self.root = root
        self.dataset = dataset
        self.thresh = thresh
        self.drug_embeddings = {}
        self.adjacency_matrix = {}

    def fit(self, train_items):
        """
        Train by building drug similarity graph from positive combinations.

        Args:
            train_items: List of dicts with keys: drugA, drugB, drugC, label
        """
        # Count drug co-occurrences in positive combinations
        drug_cooccurrence = {}
        drug_set = set()

        for item in train_items:
            if int(item.get("label", 0)) == 1:
                drugs = []
                for drug_key in ["drugA", "drugB", "drugC"]:
                    drug = str(item.get(drug_key, "")).strip()
                    if drug and drug != ".":
                        drugs.append(drug)
                        drug_set.add(drug)

                # Create edges between co-occurring drugs
                for i, d1 in enumerate(drugs):
                    for d2 in drugs[i + 1 :]:
                        pair = tuple(sorted([d1, d2]))
                        drug_cooccurrence[pair] = drug_cooccurrence.get(pair, 0) + 1

        # Normalize co-occurrence to create similarity scores
        max_cooc = max(drug_cooccurrence.values()) if drug_cooccurrence else 1
        drug_list = sorted(list(drug_set))
        n = len(drug_list)
        drug_to_idx = {drug: i for i, drug in enumerate(drug_list)}

        # Build adjacency matrix
        adj = np.zeros((n, n), dtype=float)
        for (d1, d2), count in drug_cooccurrence.items():
            similarity = float(count) / float(max_cooc)
            if similarity >= self.thresh:
                i, j = drug_to_idx[d1], drug_to_idx[d2]
                adj[i, j] = similarity
                adj[j, i] = similarity

        # Add self-loops
        np.fill_diagonal(adj, 1.0)

        self.adjacency_matrix = adj
        self.drug_list = drug_list
        self.drug_to_idx = drug_to_idx

        # Simple embedding: normalized degree
        degrees = adj.sum(axis=1)
        max_degree = degrees.max() if degrees.max() > 0 else 1
        self.drug_embeddings = {
            drug: float(degrees[drug_to_idx[drug]]) / float(max_degree)
            for drug in drug_list
        }

    def score(self, items):
        """
        Score combinations based on graph structure and drug embeddings.

        Args:
            items: List of dicts with keys: drugA, drugB, drugC

        Returns:
            List of scores (normalized to [0, 1])
        """
        if not hasattr(self, "drug_to_idx") or not self.drug_to_idx:
            return [0.0] * len(items)

        scores = []

        for item in items:
            a = str(item.get("drugA", "")).strip()
            b = str(item.get("drugB", "")).strip()
            c = str(item.get("drugC", "")).strip()

            if not all(d and d != "." for d in [a, b, c]):
                scores.append(0.0)
                continue

            # Check if drugs are in the graph
            if (
                a not in self.drug_to_idx
                or b not in self.drug_to_idx
                or c not in self.drug_to_idx
            ):
                scores.append(0.0)
                continue

            # Score based on:
            # 1. Individual drug embeddings (degree in graph)
            # 2. Pairwise graph connectivity

            ia, ib, ic = self.drug_to_idx[a], self.drug_to_idx[b], self.drug_to_idx[c]

            # Individual embeddings
            embed_score = (
                self.drug_embeddings[a]
                + self.drug_embeddings[b]
                + self.drug_embeddings[c]
            ) / 3.0

            # Pairwise connectivity
            connectivity = (
                self.adjacency_matrix[ia, ib]
                + self.adjacency_matrix[ia, ic]
                + self.adjacency_matrix[ib, ic]
            ) / 3.0

            # Combined score
            score = 0.4 * embed_score + 0.6 * connectivity
            scores.append(float(score))

        # Normalize to [0, 1]
        arr = np.array(scores, dtype=float)
        if arr.max() > 0:
            arr = arr / arr.max()

        return arr.tolist()
