# generated by copilat
"""
models_gat.py

Graph Attention Network (GAT) model for drug combination synergy prediction.

GATs use attention mechanisms to learn which neighbors are most relevant for
predicting drug combination outcomes. This is a simplified implementation for
baseline comparison.
"""

import numpy as np


class GATRunner:
    """
    GAT baseline model using drug similarity graph with attention.

    This simplified implementation:
    1. Constructs a similarity graph between drugs
    2. Uses attention weights to emphasize important connections
    3. Scores combinations based on attention-weighted aggregation
    """

    def __init__(self, root, dataset, thresh=0.1):
        """
        Initialize GATRunner.

        Args:
            root: Root directory containing data files
            dataset: 'breast' or 'lung'
            thresh: Threshold for edge creation in similarity graph (default 0.1)
        """
        self.root = root
        self.dataset = dataset
        self.thresh = thresh
        self.attention_weights = {}
        self.drug_features = {}

    def fit(self, train_items):
        """
        Train by building attention-weighted drug graph from positive combinations.

        Args:
            train_items: List of dicts with keys: drugA, drugB, drugC, label
        """
        # Count drug co-occurrences and compute attention weights
        drug_cooccurrence = {}
        drug_interactions = {}
        drug_set = set()

        for item in train_items:
            if int(item.get("label", 0)) == 1:
                drugs = []
                for drug_key in ["drugA", "drugB", "drugC"]:
                    drug = str(item.get(drug_key, "")).strip()
                    if drug and drug != ".":
                        drugs.append(drug)
                        drug_set.add(drug)

                # Pairwise interactions
                for i, d1 in enumerate(drugs):
                    for d2 in drugs[i + 1 :]:
                        pair = tuple(sorted([d1, d2]))
                        drug_cooccurrence[pair] = drug_cooccurrence.get(pair, 0) + 1

                        # For each drug, track its interaction partners
                        if d1 not in drug_interactions:
                            drug_interactions[d1] = {}
                        if d2 not in drug_interactions:
                            drug_interactions[d2] = {}

                        drug_interactions[d1][d2] = drug_interactions[d1].get(d2, 0) + 1
                        drug_interactions[d2][d1] = drug_interactions[d2].get(d1, 0) + 1

        # Normalize co-occurrence
        max_cooc = max(drug_cooccurrence.values()) if drug_cooccurrence else 1
        drug_list = sorted(list(drug_set))

        # Compute attention weights via softmax over neighbors
        self.attention_weights = {}
        for drug in drug_list:
            neighbors = drug_interactions.get(drug, {})
            if neighbors:
                neighbor_counts = np.array(list(neighbors.values()), dtype=float)
                neighbor_counts = neighbor_counts / neighbor_counts.sum()
                neighbor_drugs = sorted(neighbors.keys())
                self.attention_weights[drug] = dict(
                    zip(neighbor_drugs, neighbor_counts)
                )
            else:
                self.attention_weights[drug] = {}

        # Compute drug features: frequency-based features
        drug_frequencies = {}
        for item in train_items:
            if int(item.get("label", 0)) == 1:
                for drug_key in ["drugA", "drugB", "drugC"]:
                    drug = str(item.get(drug_key, "")).strip()
                    if drug and drug != ".":
                        drug_frequencies[drug] = drug_frequencies.get(drug, 0) + 1

        max_freq = max(drug_frequencies.values()) if drug_frequencies else 1
        self.drug_features = {
            drug: float(freq) / float(max_freq)
            for drug, freq in drug_frequencies.items()
        }

    def score(self, items):
        """
        Score combinations using attention-weighted aggregation.

        Args:
            items: List of dicts with keys: drugA, drugB, drugC

        Returns:
            List of scores (normalized to [0, 1])
        """
        scores = []

        for item in items:
            a = str(item.get("drugA", "")).strip()
            b = str(item.get("drugB", "")).strip()
            c = str(item.get("drugC", "")).strip()

            if not all(d and d != "." for d in [a, b, c]):
                scores.append(0.0)
                continue

            # Individual drug features
            feat_a = self.drug_features.get(a, 0.0)
            feat_b = self.drug_features.get(b, 0.0)
            feat_c = self.drug_features.get(c, 0.0)

            # Attention-based aggregation for each drug
            # Sum of attention weights from neighbors
            attn_a = sum(self.attention_weights.get(a, {}).values())
            attn_b = sum(self.attention_weights.get(b, {}).values())
            attn_c = sum(self.attention_weights.get(c, {}).values())

            # Combined score: features + attention
            feature_score = (feat_a + feat_b + feat_c) / 3.0
            attention_score = (attn_a + attn_b + attn_c) / 3.0

            score = 0.5 * feature_score + 0.5 * attention_score
            scores.append(float(score))

        # Normalize to [0, 1]
        arr = np.array(scores, dtype=float)
        if arr.max() > 0:
            arr = arr / arr.max()

        return arr.tolist()
