# generated by copilat

"""
models_deepsynergy.py

DeepSynergy model runner for drug combination synergy prediction.
Reference: Preuer, K., et al. "DeepSynergy: predicting anti-cancer drug synergy with Deep Learning"
Bioinformatics 34.9 (2018): 1538-1546.

This is a simplified implementation that serves as a baseline model.
The full DeepSynergy model requires:
- Drug chemical information (fingerprints)
- Cell line genomic information
- A deep neural network with specific architecture
"""

import numpy as np
import os
import pickle
from dbrwh import load_incidence


class DeepSynergyRunner:
    """
    DeepSynergy baseline model for drug combination prediction.

    This implementation uses a simplified heuristic based on:
    1. Individual drug activity in the cell line
    2. Pairwise drug interactions
    3. Combined effect prediction
    """

    def __init__(self, root, dataset):
        """
        Initialize DeepSynergyRunner.

        Args:
            root: Root directory containing data files
            dataset: 'breast' or 'lung'
        """
        self.root = root
        self.dataset = dataset
        self.drug_activity = {}
        self.pairwise_synergy = {}
        self.trained = False

    def fit(self, train_items):
        """
        Train on positive drug combinations.

        Args:
            train_items: List of dicts with keys: drugA, drugB, drugC, label
        """
        # Estimate drug activity from training data
        drug_counts = {}

        for item in train_items:
            if int(item.get("label", 0)) == 1:
                for drug_key in ["drugA", "drugB", "drugC"]:
                    drug = str(item.get(drug_key, "")).strip()
                    if drug and drug != ".":
                        drug_counts[drug] = drug_counts.get(drug, 0) + 1

        # Normalize drug activity
        max_count = max(drug_counts.values()) if drug_counts else 1
        self.drug_activity = {
            drug: float(count) / float(max_count) for drug, count in drug_counts.items()
        }

        # Estimate pairwise synergy from training triads
        pair_synergy = {}
        for item in train_items:
            if int(item.get("label", 0)) == 1:
                a = str(item.get("drugA", "")).strip()
                b = str(item.get("drugB", "")).strip()
                c = str(item.get("drugC", "")).strip()

                if all(d and d != "." for d in [a, b, c]):
                    pairs = [
                        tuple(sorted([a, b])),
                        tuple(sorted([a, c])),
                        tuple(sorted([b, c])),
                    ]
                    for pair in pairs:
                        pair_synergy[pair] = pair_synergy.get(pair, 0) + 1

        # Normalize pairwise synergy
        max_pair_count = max(pair_synergy.values()) if pair_synergy else 1
        self.pairwise_synergy = {
            pair: float(count) / float(max_pair_count)
            for pair, count in pair_synergy.items()
        }

        self.trained = True

    def score(self, items):
        """
        Predict synergy scores for drug combinations.

        Args:
            items: List of dicts with keys: drugA, drugB, drugC

        Returns:
            List of scores (0 to 1)
        """
        if not self.trained:
            return [0.0] * len(items)

        scores = []
        for item in items:
            a = str(item.get("drugA", "")).strip()
            b = str(item.get("drugB", "")).strip()
            c = str(item.get("drugC", "")).strip()

            if not all(d and d != "." for d in [a, b, c]):
                scores.append(0.0)
                continue

            # Individual drug activity scores
            score_a = self.drug_activity.get(a, 0.0)
            score_b = self.drug_activity.get(b, 0.0)
            score_c = self.drug_activity.get(c, 0.0)

            # Pairwise synergy scores
            pair_ab = self.pairwise_synergy.get(tuple(sorted([a, b])), 0.0)
            pair_ac = self.pairwise_synergy.get(tuple(sorted([a, c])), 0.0)
            pair_bc = self.pairwise_synergy.get(tuple(sorted([b, c])), 0.0)

            # Combined prediction: weighted combination
            # Individual effects (30%) + Pairwise synergies (70%)
            individual_score = (score_a + score_b + score_c) / 3.0
            pairwise_score = (pair_ab + pair_ac + pair_bc) / 3.0

            combined_score = 0.3 * individual_score + 0.7 * pairwise_score
            scores.append(float(combined_score))

        # Normalize to [0, 1]
        arr = np.array(scores, dtype=float)
        if arr.max() > 0:
            arr = arr / arr.max()

        return arr.tolist()
