# first:
check todos for example normalizing source, 2. seperating also with celline?
1. then you can seperate and split data by seperate_2_3drug_input.py
2. run enrich_features.py to get the features for drugs (atc code, target, smile)
3. run sim_builder.py to build the similarity matrices for drugs.
4. run compute_synergy_scores.py to compute the synergy scores for drug combinations. 
however, first ofi running this script you have to multiple : H * sim.

i did not run this and got synergy score 0 for top synergy:))
you have to check logic with both article and source repo
# evaluate:




# 18 May:
1. get enriched_data, (get all smiles, atc, target from drugbank for empty values, also
 check when better net is, net in my check was not good)
2. create sim_builder
3. create create hypergraph
4. run compute_synergy_scores
5. evaluate model 

# run once with limited data and run pipleine get at least one output metric 
# then create more data and run again